name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Lint Install
        run: | 
          curl -s https://raw.githubusercontent.com/wata727/tflint/master/install_linux.sh | bash
          tflint --version

      - name: Run tflint
        run: tflint

      - name: tfsec Install
        run: |
          curl -L -o tfsec

      - name: Run tfsec
        run: tfsec

      - name: Terraform Docs
        run: terraform-docs markdown table . > README.md

  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: static_analysis
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Plan
        run: terraform plan -out=terraform-plan

      - name: Save terraform plan artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: terraform-plan

      - name: Comment PR with Terraform Plan
        uses: unsplash/comment-on-pr@v1
        with:
          msg: |
            **Terraform Plan**
            \`\`\`
            $(terraform show -json terraform-plan | jq -r '.resource_changes[] | [.change.actions[], .change.after, .change.before] | @tsv' | awk '{print $1, $2, $3}')
            \`\`\`
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform_plan
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: terraform plan artifact
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan

      - name: Terraform Apply
        run: terraform apply terraform-plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
